// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	domain "github.com/xoltawn/weatherhub/internal/domain"

	uuid "github.com/google/uuid"
)

// WeatherRepository is an autogenerated mock type for the WeatherRepository type
type WeatherRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, weather
func (_m *WeatherRepository) Create(ctx context.Context, weather *domain.Weather) error {
	ret := _m.Called(ctx, weather)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Weather) error); ok {
		r0 = rf(ctx, weather)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: ctx, id
func (_m *WeatherRepository) Delete(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAll provides a mock function with given fields: ctx
func (_m *WeatherRepository) GetAll(ctx context.Context) ([]domain.Weather, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []domain.Weather
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]domain.Weather, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []domain.Weather); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Weather)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *WeatherRepository) GetByID(ctx context.Context, id uuid.UUID) (*domain.Weather, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *domain.Weather
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*domain.Weather, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *domain.Weather); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Weather)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetLatestByCity provides a mock function with given fields: ctx, cityName
func (_m *WeatherRepository) GetLatestByCity(ctx context.Context, cityName string) (*domain.Weather, error) {
	ret := _m.Called(ctx, cityName)

	if len(ret) == 0 {
		panic("no return value specified for GetLatestByCity")
	}

	var r0 *domain.Weather
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.Weather, error)); ok {
		return rf(ctx, cityName)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.Weather); ok {
		r0 = rf(ctx, cityName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Weather)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, cityName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, weather
func (_m *WeatherRepository) Update(ctx context.Context, weather *domain.Weather) error {
	ret := _m.Called(ctx, weather)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Weather) error); ok {
		r0 = rf(ctx, weather)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewWeatherRepository creates a new instance of WeatherRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewWeatherRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *WeatherRepository {
	mock := &WeatherRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
